// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SportEventApp.Data;

#nullable disable

namespace SportEventApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SportEventApp.Models.SportEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("PlayersCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SportEvents", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SportEventApp.Models.Football", b =>
                {
                    b.HasBaseType("SportEventApp.Models.SportEvent");

                    b.Property<string>("StadiumName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Team1Score")
                        .HasColumnType("integer");

                    b.Property<int>("Team2Score")
                        .HasColumnType("integer");

                    b.ToTable("FootballEvents", (string)null);
                });

            modelBuilder.Entity("SportEventApp.Models.Tennis", b =>
                {
                    b.HasBaseType("SportEventApp.Models.SportEvent");

                    b.Property<string>("CourtSurface")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CurrentGame")
                        .HasColumnType("integer");

                    b.Property<int>("Player1Score")
                        .HasColumnType("integer");

                    b.Property<int>("Player2Score")
                        .HasColumnType("integer");

                    b.Property<int>("SetsCount")
                        .HasColumnType("integer");

                    b.ToTable("TennisEvents", (string)null);
                });

            modelBuilder.Entity("SportEventApp.Models.Football", b =>
                {
                    b.HasOne("SportEventApp.Models.SportEvent", null)
                        .WithOne()
                        .HasForeignKey("SportEventApp.Models.Football", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SportEventApp.Models.Tennis", b =>
                {
                    b.HasOne("SportEventApp.Models.SportEvent", null)
                        .WithOne()
                        .HasForeignKey("SportEventApp.Models.Tennis", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
